const en = {
  translation: {
    // Nav
    nav: {
      home: "Generator",
      history: "History",
      tagline: "Your AI co-founder",
    },
    // Hero
    hero: {
      title: "Transform your idea into an\ninvestor-ready pitch",
      subtitle:
        "AI-powered platform that helps entrepreneurs craft professional business pitches in minutes.",
    },
    // Templates
    templates: {
      title: "Choose a template",
      "lean-canvas": {
        name: "Lean Canvas",
        description: "9-block business model on one page",
      },
      "elevator-pitch": {
        name: "Elevator Pitch",
        description: "30-second compelling pitch",
      },
      "investor-pitch": {
        name: "Investor Pitch",
        description: "Full deck for fundraising",
      },
      "executive-summary": {
        name: "Executive Summary",
        description: "High-level business overview",
      },
    },
    // Form
    form: {
      title: "Describe your project",
      projectName: "Project / Startup name",
      projectNamePlaceholder: "e.g. EcoRide",
      description: "What does your startup do?",
      descriptionPlaceholder:
        "Briefly describe your product or service and the problem it solves...",
      targetMarket: "Target market",
      targetMarketPlaceholder: "e.g. Urban commuters aged 20–40 in Europe",
      uniqueValue: "Unique value proposition",
      uniqueValuePlaceholder:
        "What makes your solution better than existing alternatives?",
      features: "Key features (optional)",
      featuresPlaceholder: "List 3–5 core features...",
      provider: "AI provider",
      providerFallbackNote:
        "If your chosen provider has no credit, the system automatically switches to the next available one.",
      generate: "Generate pitch",
      generating: "Generating…",
    },
    // Result
    result: {
      generatedBy: "Generated by {{model}}",
      copy: "Copy",
      copied: "Copied!",
      exportTxt: "Export TXT",
      exportPdf: "Export PDF",
      exportJson: "Export JSON",
      save: "Save to history",
      saved: "Saved!",
      regenerate: "Regenerate",
      fallbackBadge: "Auto-switched → {{provider}}",
      fallbackTooltip:
        "{{requested}} had no credit — automatically switched to {{used}}",
    },
    // History
    history: {
      title: "Saved pitches",
      empty: "No saved pitches yet. Generate your first pitch!",
      delete: "Delete",
      open: "Open",
    },
    // Errors
    errors: {
      generic: "Something went wrong. Please try again.",
      noProvider: "No AI provider is available. Configure at least one API key.",
      validation: "Please fill in all required fields.",
    },
    // Footer
    footer: {
      tagline: "Craft investor-ready pitches with AI",
      madeWith: "Made with",
    },
    // Misc
    language: "Français",
  },
};

export default en;
